"use client";

/**
 * TabsCard
 *
 * Concept port of a Framer.com canvas-generated component ("Tabs card") —
 * like the other "generated by Framer" ports in this folder, the original
 * is a canvas export coupled to Framer-internal sub-components (a nested
 * `Tabs` module, Framer's `Image` component, `useVariantState`, ...), not
 * portable as-is. This rebuilds the same idea: a column of clickable tabs
 * (title + description), each swapping the image shown alongside it, with
 * a crossfade on change.
 *
 * npm i framer-motion
 */

import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";

export interface TabCardItem {
  title: string;
  description: string;
  image: string;
  alt?: string;
}

export interface TabsCardProps {
  items: TabCardItem[];
  /** Index of the tab selected initially. Default 0. */
  defaultIndex?: number;
  className?: string;
  style?: React.CSSProperties;
}

export function TabsCard({ items, defaultIndex = 0, className, style }: TabsCardProps) {
  const [active, setActive] = useState(defaultIndex);
  const current = items[active];

  return (
    <div
      className={className}
      style={{
        display: "flex",
        gap: 24,
        background: "rgb(255,255,255)",
        borderRadius: 24,
        padding: 8,
        maxWidth: 1104,
        ...style,
      }}
    >
      <div style={{ display: "flex", flexDirection: "column", gap: 4, flex: "1 0 0", paddingTop: 40 }}>
        {items.map((item, i) => {
          const isActive = i === active;
          return (
            <button
              key={item.title}
              onClick={() => setActive(i)}
              style={{
                textAlign: "left",
                display: "flex",
                flexDirection: "column",
                gap: 4,
                padding: "16px 18px",
                borderRadius: 16,
                border: "none",
                cursor: "pointer",
                background: isActive ? "rgba(0,0,0,0.04)" : "transparent",
                transition: "background 0.2s ease",
              }}
            >
              <span style={{ fontSize: 16, fontWeight: 600, color: isActive ? "#0a0a0c" : "rgba(10,10,12,0.55)" }}>
                {item.title}
              </span>
              <AnimatePresence initial={false}>
                {isActive && (
                  <motion.span
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    style={{ overflow: "hidden", fontSize: 14, color: "rgba(10,10,12,0.6)", lineHeight: 1.5 }}
                  >
                    {item.description}
                  </motion.span>
                )}
              </AnimatePresence>
            </button>
          );
        })}
      </div>

      <div
        style={{
          flex: "1 0 0",
          position: "relative",
          borderRadius: 24,
          overflow: "hidden",
          background: "rgb(226,232,240)",
          minHeight: 320,
        }}
      >
        <AnimatePresence mode="wait">
          <motion.img
            key={current.image}
            src={current.image}
            alt={current.alt ?? current.title}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.35, ease: "easeInOut" }}
            style={{ position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover" }}
          />
        </AnimatePresence>
      </div>
    </div>
  );
}

export default TabsCard;
